version: '3'
services:
  #nginx反向代理
  nginx:
    container_name: bknife-nginx
    image: nginx
    volumes:
      - /etc/nginx:/etc/nginx
      - /www:/www
      - /etc/ssl:/root/cert
    ports:
      - 80:80/tcp
      - 443:443/tcp
    networks:
      - bknife

  #xray管理页面
  x-ui:
    container_name: bknife-xray
    image: enwaiax/x-ui
    volumes:
      - /etc/x-ui:/etc/x-ui
      - /etc/ssl:/root/cert
    ports:
      - 8388-8400:8388-8400/tcp
      - 8388-8400:8388-8400/udp
    networks:
      - bknife
    depends_on:
      - nginx

  #docker管理器
  portainer:
    container_name: bknife-portainer
    image: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.portainer_data:/data
    ports:
      - 8000:8000
    networks:
      - bknife
    depends_on:
      - nginx

networks:
  bknife:
    name: bknife
